### ISSUE TITLE
Extra /'s added to URL on X-Post

### ISSUE THREAD

**Issue by DizzyZane** [iGGNoRe/shareddit#7]
This happens every time.

https://www.reddit.com/r/applesucks/comments/3nadsh/meta_please_stop_posting_links_to_clickbait/
https://www.reddit.com/r/pcmasterrace/comments/3n2p6d/somebody_is_making_pok%C3%A9mon_red_in_minecraft/
Very annoying Any way to fix?

**Comment by iGGNoRe** [comment]
The extensions remove those automatically, but I suppose they can just be removed from the raw bookmark script code. They are to get around reddit's "duplicate submission" tests, but like I said they currently are only able to be removed by the extensions, or if you run the bookmarklet again on the submission page.
